export const FETCH_IMAGES_START = 'FETCH_IMAGES_START';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGES_FAILED = 'FETCH_IMAGES_FAILED';

export const SAVE_SEARCH_QUERY = 'SAVE_SEARCH_QUERY';

